django_http_exceptions/__init__.py,sha256=y18YyJMepwIS1dT5M9Mp0tM2R6gZ0SlKNuK7jbQz_gQ,361
django_http_exceptions/_exceptions.py,sha256=BKSebxOX9DGDa0-OgufGJbFJHsdj-133hTtPX3b3HvI,2923
django_http_exceptions/exceptions.py,sha256=pWtK-TT9aXzRU08AlODb5B0sJ59ZuJwv2arHashvxsM,4271
django_http_exceptions/middleware.py,sha256=c5q8adDTogQqlKsgWF3DbsrgJ2zkStIWBhMjjVR1i98,1326
django_http_exceptions/utils.py,sha256=97TmtNJQzzhsMZD0zFJfJRGrQv1zCBsjfXssOVH1Mlc,576
django_http_exceptions-1.4.2.dist-info/LICENSE,sha256=oSw9ZskCEr1Zn7THwudx15RAyEs6Ip-RZM8g9ZQRwUA,1051
django_http_exceptions-1.4.2.dist-info/METADATA,sha256=b9ArnN74B977QVzoeChL8QPWWdmCbdiAhsA4YkduYpE,9851
django_http_exceptions-1.4.2.dist-info/WHEEL,sha256=R06PA3UVYHThwHvxuRWMqaGcr-PuniXahwjmQRFMEkY,91
django_http_exceptions-1.4.2.dist-info/top_level.txt,sha256=P3TrW6xS37vWtFiQe4mzx6mEjXAR_V7E3PjidjnynbQ,23
django_http_exceptions-1.4.2.dist-info/RECORD,,
